<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <RootNamespace>Sample.Avalonia</RootNamespace>
    <TargetFramework>net10.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sample.Avalonia\Sample.Avalonia.csproj" />
  </ItemGroup>
</Project>
